# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

WORKDIR /app

# install dependencies
RUN pip install --no-cache-dir mcp[cli] python-dotenv redshift-connector

# copy source code
COPY src/ src/
COPY README.md .

# default command (overridden by MCP runtime)
CMD ["python","-u","src/redshift_mcp_server/server.py"]
